### ISSUE TITLE
Dependencies in BearRiver

### ISSUE THREAD

**Issue by mkm0815** [ivanperez-keera/dunai#2] opened 2016-07-14 15:34 UTC
Hi all,
BearRiver does not include Dependencies  (random, deepSeq) that Yampa does.
It would be great if I could just swap Yampa with BearRiver in the cabal file without adding these dependencies too. 
Instead a package BearRiverDepenencies could also be created, that just has dependencies on BearRiver, random & deepSeq

**Comment by ivanperez-keera** [comment] 2017-09-17 20:15
There's no reason why they should not be there. They are only missing because bearriver is smaller (for now). Pull request?

**Comment by turion** [comment] 2017-10-06 13:00
I don't see what the advantage is. If you add dependencies, e.g. deepSeq, to BearRiver, you still can't use deepSeq in a project that uses BearRiver, right? You need to add deepSeq to your projects dependencies anyways, so nothing is gained. But installation time of bearriver goes up.

**Comment by ivanperez-keera** [comment] 2017-10-06 16:24
The fact that the dependency is not there is a sign that something's missing in BearRiver.

What I'm saying is not add a useless dependency, but make it necessary by implementing what's missing.

**Comment by turion** [comment] 2017-10-09 07:52
The `deepSeq` dependency is related to #20 (closed for now), I guess. Yampa uses `random` to create random noise streams, so the remainder of this issue is implementing random noise streams for BearRiver.

**Comment by ivanperez-keera** [comment] 2017-10-22 22:30
Ok. Let's approach this differently. The problem is that BearRiver currently does not implement Yampa fully. That's the issue.

Closing this now, opening a new issue.

**Closed by ivanperez-keera** 2017-10-22 22:30 UTC
