### ISSUE TITLE
iPostKleisli and corresponding naming issue

### ISSUE THREAD

**Issue by turion** [ivanperez-keera/dunai#34] opened 2017-10-18 15:46 UTC
We have `iPost :: b -> MSF m a b -> MSF m a b` which ignores the first input and outputs `b` instead. This can be generalised to `iPostM :: m b -> MSF a b -> MSF a b` (probably uncontroversial) and further to `iPostKleisli :: (a -> m b) -> MSF a b -> MSF a b`.

My question is whether...

* this should be added to `Data.MonadicStreamFunction` as a fundamental building block,
* or it should be implemented in a high-level way in terms of exceptions (potential efficiency issue).

Furthermore:

* Should `iPost` be defined in terms of it (potential minor efficiency issue)?
* What's a better name for it? 
  * Note that it's a lot like `(:) :: a -> [a] -> [a]`, so one might be tempted to write it like a list construction operator.

**Comment by ivanperez-keera** [comment] 2017-11-01 14:18
Let's keep this one out for now. If during the re-structuring we see that it belongs elsewhere, then we can move it.

Subticket/duplicate of: https://github.com/ivanperez-keera/dunai/issues/53

**Closed by ivanperez-keera** 2017-11-01 14:18 UTC
Labels: question
